import json
import os
import subprocess
import requests

# Config
GITHUB_TOKEN = os.getenv("GH_TOKEN")
COPILOT_API_URL = "https://api.github.com/copilot/chat/completions"

def ask_copilot(finding, file_content):
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}", # 'token' instead of 'Bearer' for Classic
        "Accept": "application/vnd.github+json"
    }
    
    # Rest of the payload stays the same
    payload = {
        "model": "gpt-4o",
        "messages": [{"role": "user", "content": f"Fix: {finding}\n\nCode:\n{file_content}"}]
    }
    
    response = requests.post(COPILOT_API_URL, headers=headers, json=payload)
    if response.status_code == 404:
        return "ERROR: Copilot API not accessible with this token. Check SSO or Org Policies."
    return response.json()['choices'][0]['message']['content'].strip()

def run():
    # Load findings
    if not os.path.exists('mobsf_results.json'):
        print("No findings found.")
        return

    with open('mobsf_results.json') as f:
        findings = json.load(f).get('results', [])

    if not findings:
        print("Zero vulnerabilities detected.")
        return

    # To keep it clean, we fix the FIRST high-severity finding found
    # You can loop through all, but one-at-a-time is safer for AI accuracy
    issue = next((f for f in findings if f.get('severity') == 'high'), findings[0])
    
    file_path = issue['file_path']
    description = issue['description']
    branch_name = f"mobsf-fix-{os.urandom(2).hex()}"

    print(f"Creating fix for: {description} in {file_path}")

    # Git Setup
    subprocess.run(["git", "checkout", "-b", branch_name])

    with open(file_path, 'r') as f:
        original_code = f.read()

    # Get Fix from Copilot
    new_code = ask_copilot(description, original_code)

    with open(file_path, 'w') as f:
        f.write(new_code)

    # Push and PR
    subprocess.run(["git", "add", file_path])
    subprocess.run(["git", "commit", "-m", f"Security fix: {description}"])
    subprocess.run(["git", "push", "origin", branch_name])
    
    pr_title = f"🛡️ MobSF Security Fix: {description[:50]}"
    pr_body = f"This PR was generated by Gemini & Copilot based on MobSF findings.\n\n**Issue:** {description}"
    
    subprocess.run(["gh", "pr", "create", "--title", pr_title, "--body", pr_body, "--head", branch_name])

if __name__ == "__main__":
    run()
